### ISSUE TITLE
BENSYC - Draft Terms

### ISSUE THREAD

**Issue by Web3Master** [bensyc/bensyc#1]
[Bored ENS Yacht Club - Terms (Draft).docx](https://github.com/bensyc/bensyc/files/9351938/Bored.ENS.Yacht.Club.-.Terms.Draft.docx)

Modified from MAYC.  Deleted Arbitration provisions. 
 Potentially consider adding a venue/jurisdiction clause

**Comment by sshmatrix** [comment]
T&C added to hackmd group
